apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: configurablehorizontalpodautoscalers.configurablehpa.k8s.io
spec:
  group: configurablehpa.k8s.io
  names:
    kind: ConfigurableHorizontalPodAutoscaler
    plural: configurablehorizontalpodautoscalers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cpuInitializationPeriodSeconds:
              format: int32
              maximum: 120
              minimum: 1
              type: integer
            delayOfInitialReadinessStatusSeconds:
              format: int32
              maximum: 120
              minimum: 1
              type: integer
            downscaleLimit:
              format: int32
              maximum: 100
              minimum: 2
              type: integer
            downscaleStabilizationWindowSeconds:
              format: int32
              maximum: 600
              minimum: 1
              type: integer
            tolerance:
              format: double
              maximum: 0.99
              minimum: 0.01
              type: number
          required:
          - downscaleStabilizationWindowSeconds
          type: object
        status:
          properties:
            currentReplicas:
              format: int32
              type: integer
            desiredReplicas:
              format: int32
              type: integer
            lastScaleTime:
              format: date-time
              type: string
            observedGeneration:
              format: int64
              type: integer
          required:
          - currentReplicas
          - desiredReplicas
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
