apiVersion: configurablehpa.k8s.io/v1beta1
kind: ConfigurableHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: configurablehorizontalpodautoscaler-sample
spec:
  downscaleStabilizationWindow: 15
  downscaleLimit: 5
  tolerance: 0.1
  cpuInitializationPeriod: 15
  delayOfInitialReadinessStatus: 15
